M48
; DRILL file {KiCad (6.0.11)} date Fri Feb 10 17:53:28 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-02-10T17:53:28-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.500
%
G90
G05
T1
X118.037Y-55.1G85X118.037Y-55.9
G05
X129.338Y-55.1G85X129.338Y-55.9
G05
T0
M30
